### ISSUE TITLE
Unable to built Next.js since upgrading to v2

### ISSUE THREAD

**Issue by peduarte** [kripod/react-polymorphic-box#11]
Hey @kripod 

As you probably have seen I've been contributing to [Stitches](https://github.com/christianalfoni/stitches) recently to help test it and make sure things are working as users would expect.

@christianalfoni has been working on improving the types and as part of the latest Stitches release, he upgraded to `react-polymorphic-box v2.0.3`

Since this upgrade, I'm unable to get my Next.js project to build correctly. Things were working fine before that. We suspect it's something to do with the new build strategy used in v2. 

I've abstracted a reproducible [branch in this repo](https://github.com/peduarte/interop-stitches/tree/react-polymorphic-box-v2) which you're free to clone and test it out.

Do you think this could be related to the latest release?

Let me know if there's any way I can help.

**Comment by kripod** [comment]
Hello,

Thank you for reporting! For v2, I’ve changed the bundling and distribution mechanism. Unfortunately, this may have resulted in broken builds in some environments.

Currently, I’m on a vacation for 3 days, so I will take a look at `package.json` (e.g. ‘cjs’ vs. ‘mjs’ file extensions and the use of `"type": "module"`) as soon as I get home.

**Comment by peduarte** [comment]
@kripod sure, no rush. Thanks and enjoy the holidays! We've done a patch on our side for now 👍

**Comment by kripod** [comment]
Lovely, thank you! 🙌

May I ask how the patch works? That may take us closer to resolving the situation.

**Comment by peduarte** [comment]
This is [the commit](https://github.com/christianalfoni/stitches/commit/d0f961f03cf6f3d8e86ed1a1136d96298f17ba29) for it. It reverts to v1 😄 

Plus it adds the types that Christian had added in [this PR](https://github.com/kripod/react-polymorphic-box/pull/10)

**Comment by kripod** [comment]
This should be resolved by v2.0.4. Thank you for reporting and please reach out if you encounter any further issues.

Christian and you are doing awesome work with Stitches. I hope it will get big, especially with the recently added support for object syntax.

**Comment by peduarte** [comment]
Thanks @kripod will test it and get back to you! :)
