### ISSUE TITLE
Function types are typed as any

### ISSUE THREAD

**Issue by mattcompiles** [kripod/react-polymorphic-box#13]
## Description

Function types (e.g. event handlers) are typed as any. I'm not convinced `react-polymorphic-box` is at fault here but thought I'd raise it to discuss. In my example typescript seems to infer the correct type for the event handler (pictured below), however when implementing the handler it is not typed.

![image](https://user-images.githubusercontent.com/8802980/87494003-58c3b580-c691-11ea-9a1c-7c15f924e01a.png)

## Reproduction

```tsx
import React from 'react';
import { Box } from 'react-polymorphic-box'; 

const Test = () => (
  <Box
    as="li"
    onMouseDown={(event) => {
      // event is implicitly typed as any
    }}
  />
);
```

## Expected behaviour

The event handler should be typed as expected.

## Actual behaviour

Event handlers seem to be typed as any. 

![image](https://user-images.githubusercontent.com/8802980/87494514-907f2d00-c692-11ea-9437-324499b17e8a.png)

## System:
 - OS: macOS Mojave 10.14.6
 - CPU: (8) x64 Intel(R) Core(TM) i7-8559U CPU @ 2.70GHz
 - Memory: 42.69 MB / 16.00 GB
 - Shell: 5.3 - /bin/zsh
## Binaries:
 - Node: 12.18.2
 - Yarn: 1.22.4
 - npm: 6.14.5 
## Browsers:
 - Chrome: 84.0.4147.89
 - Firefox: 78.0.1
 - Safari: 12.1.2
## npmPackages:
 - react-polymorphic-box: ^2.0.4 => 2.0.4 
 - typescript: 3.9.6

**Comment by kripod** [comment]
Thank you for submitting this issue! [As far as I know](https://github.com/christianalfoni/stitches/issues/43#issuecomment-655417176), this might be fixed on the language level by a forthcoming release of TypeScript. Please follow https://github.com/microsoft/TypeScript/pull/31023 for more information!

**Comment by mattcompiles** [comment]
Cheers bud, you're all over it. 👍

**Comment by corbanbrook** [comment]
This is what i did to get event handlers to type correctly.

[playground link](https://www.typescriptlang.org/play?#code/JYWwDg9gTgLgBAJQKYEMDGMA0cDec1SoxICiANkiEgHZZwBm0A7ilACbL3bmU0wAqATzBJsAYQjgI1PgAUoEMAGcA6sBgALTuMmQZteYtXqNEAK4xtiJF2voYPKrWzJ7AOQhskcAL4MFIHAA5IT2QQDcAFCRAPQxcACCMJLAaPhKSvhkKBlImZHAtEhQ9OjeSZKZOJFwtXBswEpg2YIA-ABcwYVkhUhBcAA+wQBGZBBoANb9Q0HdvQC0o+NTg8H0FAAe08EA5lDAbEE1dUwHmh3BKBYQ20H0ZmRkR3VwGkjAOxowF0FXybf3R7POrDaBeKAIFANMxKH5KEC3ECHVZBMg7W5oYBQNAUYG1UHsYpqNjnTpBTSFW4UyZ4uBgKENag7OEIlFI25o2kgVg7QosxHImac461OK1JAwNAAOilkR80TFYhQ1GoEHgMO8Eik+hghmUak0nDg0jgyTAcAoADckGQ4MMLHAmN40NIlDAoGYMHAUKbhN4mBpUho4IUcWYvJlNN5CPRTYHMixBJEYH64AAhCAbPVKAA8-DgSA2xGobEyjj4QhEcAAvMEGpaggA+GsiuBavRyBT6kzmSw2PPNgBkuFbLxyF34o7qMYunBz7eknaMBq0-f4jYA2iEbEEALrNobUB62xW6RcGLvGQ02OAatgh6hKA7eRoMXqtvzDiogJTRFNV2QIDIQQQGgMBAzQbMc1kbB80LYtSzgctaErJBm1rWQ4GHDMs0vAc-1TQDgNAqBwNSBcdWg7AABECyLGhEOQgRU1rIJ6ybGs4DzOiELLCgnGYqta2oxsAAowEvToiJAsCIKgmC4HXABKGtG1bVwMCY1Yj0eAiAKAmTSIguc4Poks+N4FCWLrYAG3Q9NMyg9ctxjPdoi8HFWGdV14BxJQNk6USZSlTyMjcFAqCUTo3X2JkN13FTq2bGLCh2SIPOyQh8B871kh-To8AkxRihgYA8gK14ckCiYkEEaL3VSxLm1BIDUGoXwOuHUTxMk3A4A3ABpB84BqwQIFjb8lF3TpJsG3cfCauAUqZJTohdR94BwqSDJIsi0AovgcxwHxsDY2yONrRgoBYdhOFE45uPghiLIE1CxKK5ROhwpzG2wGNOjnAAJfgAFkABkmMbRbqheda3T6nJOLOhtsFCpRwqobBgsIN1sw62sPt-WGcpQPLswBpAXXYHNlp2bAzGoCZVSYah7OO1s4fgahSdspByesKm2BphqmXpxnmdZzj2dbK64FEzmRtq4acd1S8VJhl4Q1jUTScqKUPpKsqlClDQclE0bvUyUbxsSPKlCU9Wp1qXWQGzDdRt3TiVbdi3Eet2N-yQG3vcvXcpz8G0lG8DXNbgbnSutH3as92sQ6Md2lb92qbcD4O8lVoww9j+UXnlDmSby8jslyTJaxdpRRJjupgpd7MP1W1tCBgMwoHaggiFIfi+B1pRsCb2o0YxpBOj8jYdcr-bq6j0eshydGIqQJTMCnYL4957Nt9jmN2+OeUO7Ffh88yNAcjyNacrBwoJk4nqjAq5J6tinZwnwQMyDYQg1BZyoAwB4LwvhoadwlD3dqokcw+g0DGasAAiAAxMg401AxA9EmNWHAolFpw1alKMYOxX7KClMkJSPg1Kx1qDgQmIU-4AJoCXOoOYYgoChnKPS3g0wWGSNQPGtYm6WlYMAZU3wyQSVAKwQQtxVRQG5E8VsT4ABeSB+RskFMEYULxsjDBtJ-VKPDIgK34TAQR21iKyXImeSiFjBEHxGAI6QF0GDMFYBwGw90XiPTMoxIeVkRDvV6tJXack8KOOkM49cf0bDWMMntEyUNVIjmJhtBGtcXGWLcdgMR+xJFI0UcooI2B1HeFrMgpEyDsAGJtFjGUKt8Z0kvNEF4XcYFy1bDmHCls8E5D8JPDeeCCkSNoHAAA1EtYAGi-BIJwDGPwOBsb5xoU7XA9SyBsNqBwnCtC6irQWvfTJl83TZIIWk3x7CDminiAAARgEoeYhYRAYBeVABQUA4DzDgAAA0QTYP5IZMiqngD6MRPR7wfQ8d82Y1AwAWFpL0zM-TkGFERTADBgL6AoIwTEW5cAel9JyCgjFFgMGBxQcQIs+K1LEtRaS5BKAMHSGwakCYeCkCWjSdyvwBK4Cnk+ZTGAwFfQiEyNymglUSwUCgL+VsYpHnPNeSKj5Xyfn-L4MUAatVAaFBgMCkAMJ4CGO9HASFBwLUoDIGYJADKNhovJVigsRQoC6sEPq2gKCNBmA0HS9p7CSVKDJQiilrriDur1QalBUdWBoH9YK+lfjontS2SgwGNoxgYLGZIlBMjuRQEEBghZMY0lLIJYGu5cBlUvI2G8mA6roCaoBTGDYwLXxgvNZa6FXZYX-JQH8h1aKWWvDbSgmIpgqABsVQ8p5daG1Nu+b81tQK4DGvhman0tNh1MtHTivBABWflyag2MpDcy7FSDkGTskEgGdLwlXztVe84oGqV3JA7ZkEAjRUr+EkP8x+jMh0pvPXgoDEwaGAzvXszMp7q21pfY2t9zaV04q-XHNU3abVWphbLP5EGQNnsdaSnAEG-AHpvVO+9jZoNUFgxseDXFg3gafn4ZIE7qPINozBmI+yq2CrnSq+taqUPLv+Q0JoLR20gsw+C61UKlqOo+kR3ZfTJPNBQIIDYKCliTAfXUMUnAibEbgKWm8SUzM2BPbui9o7zOxks0spNtnQ2YpLTYPBZanPWZc6BkjIayNsdNBATjd6PO4sWRZ5szmBVijLa+BmTMIAswE701x7U91Xs81RrNEAMHpuQZmx4+XMHstwfg7li0+UudnTW59InX2fNQ-8z9smf0ZD-fQAIcBCPEoy-0oLjM-CFeK9m2rKaBukfIyFzjeWCsoEMWQDN82-PsMrUpIAA)
