### ISSUE TITLE
Best approach to creating a hierarchy of components

### ISSUE THREAD

**Issue by allforabit** [kripod/react-polymorphic-box#16]
Hi I'm just wondering what the best way to approach building up a hierarchy of components would be. I.e. start off with the polymorphic box as the top level item and then compose this into a very basic "view" component and use this "view" component as the basis for all other components (in an approach similar to "styled system"). Would I be better creating my own polymorphic box for this root component?

Here's an approach I started to make:

```typescript
interface ViewOwnProps {
  px?: "0" | "1";
  py?: "0" | "1";
}

export type ViewProps<E extends React.ElementType> = PolymorphicComponentProps<
  E,
  ViewOwnProps
>;

const viewDefaultProp = "div";

function View<E extends React.ElementType = typeof defaultElement>({
  px,
  py,
  ...restProps
}: ViewProps<E>): JSX.Element {
  return (
    <Box
      as={viewDefaultProp}
      {...restProps}
      style={{ padding: `${px} ${py}` }}
    />
  );
}

// Component-specific props should be specified separately
interface HeadingOwnProps extends ViewOwnProps {
  color?: string;
}

// Merge own props with others inherited from the underlying element type
export type HeadingProps<
  E extends React.ElementType
> = PolymorphicComponentProps<E, HeadingOwnProps>;

// An HTML tag or a different React component can be rendered by default
const defaultElement = "div";

function Heading<E extends React.ElementType = typeof defaultElement>({
  color,
  style,
  ...restProps
}: HeadingProps<E>): JSX.Element {
  // The `as` prop may be overridden by the passed props
  return (
    <View as={defaultElement} style={{ color, ...style }} {...restProps} />
  );
}
```

Here I create a heading that uses the view component and uses the various polymorphic box type utilities but also extends the heading own props from the view own props.

**Comment by kripod** [comment]
Thank you for the question!

Your approach seems to be good for me. The `Box` component could be used as a basis for creating a custom `View` as outlined above. If you would like to reduce the amount of abstractions, you may inline the [implementation of `Box`](https://github.com/kripod/react-polymorphic-box/blob/caa54c2c8a316e2ab0f903371022c9ef7c97cefe/src/Box.tsx#L14-L21) on your own, while importing the usual types from react-polymorphic-box.
