### ISSUE TITLE
Suggestion: PolymorphicComponent type

### ISSUE THREAD

**Issue by biowaffeln** [kripod/react-polymorphic-box#4]
## Motivation

Hi! First of all, thanks for the library, I spent quite a few hours thinking about how to solve this problem myself, and it's nice to see a community solution.

I tried out the library with styled-components and figured it would make sense to export a `PolymorphicComponent` type as well as `PolymorphicComponentProps`. A simple implementation would look like this:

```ts
export type PolymorphicComponent<P, D extends React.ElementType = "div"> = <
  E extends React.ElementType = D
>(
  props: PolymorphicComponentProps<E, P>
) => JSX.Element;
```

I found this to be especially handy when working with external libraries that already expose polymorphic components.

## Basic Example

The Heading example from the README with styled-components would look like this:
```tsx
import styled from "styled-components";

type HeadingProps = { color?: string };
const defaultElement = "h2";

const Heading: PolymorphicComponent<
  HeadingProps,
  typeof defaultElement // optional, defaults to "div"
> = styled(defaultElement)<HeadingProps>`
  color: ${(props) => props.color};
`;
```

which makes the whole API a bit more concise since you don't have to manually merge props.
I have some time on my hands rn, so if you think it's a sensible addition I could make a pull request and add some docs.

**Comment by kripod** [comment]
Great idea, I'm in for it! I'd appreciate if you could open a pull request and write the corresponding docs, including a use-case.
