### ISSUE TITLE
Missing Types on PolymorphicComponent

### ISSUE THREAD

**Issue by biowaffeln** [kripod/react-polymorphic-box#6]
I just realized that `PolymorphicComponent` is missing React's component attributes (`defaultProps`, `displayName`, etc.). One should probably add `React.ComponentType` as an intersection type to the definition.

**Comment by kripod** [comment]
Thanks for the submission! It turns out that `PolymorphicComponent<P> & React.ComponentType<P>` can be used for resolving this problem, as explained in #7.
